refactor: :fire: removiendo el ^ de las dependencias
ogticrd/sdd-kit pull request #28
Opened 2024-04-04 02:36 UTC by Victor1890

## Description
Eliminando el **^** de las dependencias

## Motivation and Context
Evitamos versiones de dependencias maliciosas o defectuosas como **la version maliciosa de faker**

2024-04-25 14:18 UTC, akevinieron commented
Hola @Victor1890. Gracias por tu aporte.

Tienes razón al sugerir este cambio. Sin embargo, nos parece más razonable cambiar el "^" por "~" que es un punto medio entre estar actualizado y un poco más seguro. 

Por favor, realiza el cambio para aceptar el PR.

2024-04-25 14:19 UTC, akevinieron requested changes
Hola @Victor1890. Gracias por tu aporte.

Tienes razón al sugerir este cambio. Sin embargo, nos parece más razonable cambiar el "^" por "~" que es un punto medio entre estar actualizado y un poco más seguro.

Por favor, realiza el cambio para aceptar el PR.

2024-04-30 02:31 UTC, Victor1890 commented
¡Hola @akevinieron, gracias por tu observación!

Actualmente, ya he aplicado los cambios sugeridos y ya he hehco el PR

2024-04-30 17:36 UTC, akevinieron commented on pnpm-lock.yaml
Por qué estás eliminando esto?

2024-05-01 13:44 UTC, Victor1890 commented on pnpm-lock.yaml
@akevinieron el archivo `pnpm-lock.yaml` no está incluido en el PR, por lo que rompe el proposito del PR

2024-05-05 21:00 UTC, akevinieron commented on pnpm-lock.yaml
De hecho si, literalmente se eliminaría el archivo del repositorio

2024-05-07 02:28 UTC, Victor1890 commented on pnpm-lock.yaml
En ese caso, he añadido un nuevo PR añadiendo el archivo `pnpm-lock.yaml`

2025-12-21 17:31 UTC, closed without merging